# Import Tensorflow

In [1]:
import tensorflow as tf

## Tensor bernilai random dengan shape (5, 5)

### 1. Metode random.normal

In [3]:
random_tensor = tf.random.normal([5, 5])
random_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 0.29763275,  0.85498464,  0.09854912, -2.7126358 , -0.24042815],
       [-1.1271733 , -0.8683328 , -1.1545057 , -0.5827167 , -0.7756453 ],
       [ 0.77041763,  1.3126546 ,  0.29093707, -1.0784489 , -0.4293769 ],
       [ 0.46234745,  1.4649199 , -0.9163859 , -0.8367941 , -0.44611695],
       [ 0.5122678 ,  0.5717116 , -0.3560064 , -0.03834996, -0.5251247 ]],
      dtype=float32)>

### 2. Metode random.uniform

In [4]:
random_tensor = tf.random.uniform([5, 5])
random_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0.38000906, 0.01690042, 0.46101856, 0.63152313, 0.9323783 ],
       [0.560354  , 0.23430037, 0.9481448 , 0.41055346, 0.99287283],
       [0.6075758 , 0.87704134, 0.3661852 , 0.73796856, 0.24635792],
       [0.21938908, 0.32215166, 0.06580174, 0.5901984 , 0.5653715 ],
       [0.9721272 , 0.9195545 , 0.02515137, 0.02007091, 0.6003431 ]],
      dtype=float32)>

## Tensor bernilai bilangan prima dengan shape (5, 5)

In [11]:
prime_tensor = tf.constant([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97], shape=[5, 5], dtype=tf.float32)
prime_tensor.numpy()

array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]], dtype=float32)

## Menampilkan dimensi dari kedua variabel tensor diatas

### 1. Dimensi tensor random

In [12]:
random_tensor.get_shape()

TensorShape([5, 5])

### 2. Dimensi tensor bilangan prima

In [13]:
prime_tensor.shape

TensorShape([5, 5])

##  Hasil perhitungan aritmetika dari 2 variable

### 1. Penjumlahan

In [14]:
tf.add(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 2.3800092,  3.0169005,  5.4610186,  7.631523 , 11.932379 ],
       [13.560354 , 17.2343   , 19.948145 , 23.410553 , 29.992872 ],
       [31.607576 , 37.87704  , 41.366184 , 43.73797  , 47.246357 ],
       [53.21939  , 59.32215  , 61.065804 , 67.590195 , 71.56537  ],
       [73.97213  , 79.919556 , 83.025154 , 89.02007  , 97.60034  ]],
      dtype=float32)>

### 2. Pengurangan

In [15]:
tf.subtract(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ -1.619991 ,  -2.9830995,  -4.5389814,  -6.368477 , -10.067621 ],
       [-12.439646 , -16.7657   , -18.051855 , -22.589447 , -28.007128 ],
       [-30.392424 , -36.12296  , -40.633816 , -42.26203  , -46.753643 ],
       [-52.78061  , -58.67785  , -60.934196 , -66.409805 , -70.43463  ],
       [-72.02787  , -78.080444 , -82.974846 , -88.97993  , -96.39966  ]],
      dtype=float32)>

### 3. Perkalian

In [16]:
tf.multiply(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[7.6001811e-01, 5.0701261e-02, 2.3050928e+00, 4.4206619e+00,
        1.0256161e+01],
       [7.2846022e+00, 3.9831064e+00, 1.8014751e+01, 9.4427299e+00,
        2.8793312e+01],
       [1.8834848e+01, 3.2450531e+01, 1.5013593e+01, 3.1732649e+01,
        1.1578822e+01],
       [1.1627622e+01, 1.9006948e+01, 4.0139060e+00, 3.9543293e+01,
        4.0141376e+01],
       [7.0965286e+01, 7.2644806e+01, 2.0875640e+00, 1.7863110e+00,
        5.8233280e+01]], dtype=float32)>

### 4. Pembagian

In [17]:
tf.divide(prime_tensor, random_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[   5.2630324,  177.51038  ,   10.845551 ,   11.084312 ,
          11.797787 ],
       [  23.199621 ,   72.556435 ,   20.039133 ,   56.02194  ,
          29.208172 ],
       [  51.02244  ,   42.187294 ,  111.9652   ,   58.268066 ,
         190.77934  ],
       [ 241.57994  ,  183.14355  ,  927.02716  ,  113.52115  ,
         125.58114  ],
       [  75.093056 ,   85.91117  , 3300.0188   , 4434.2783   ,
         161.57426  ]], dtype=float32)>

### 5. Modulus

In [23]:
tf.truncatemod(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0.38000906, 0.01690042, 0.46101856, 0.63152313, 0.9323783 ],
       [0.560354  , 0.23430037, 0.9481448 , 0.41055346, 0.99287283],
       [0.6075758 , 0.87704134, 0.3661852 , 0.73796856, 0.24635792],
       [0.21938908, 0.32215166, 0.06580174, 0.5901984 , 0.5653715 ],
       [0.9721272 , 0.9195545 , 0.02515137, 0.02007091, 0.6003431 ]],
      dtype=float32)>

## Nilai maksimal dan minimal dari variable random_tensor

### 1. Nilai Maksimum

In [31]:
tf.reduce_max(random_tensor, axis=None)

<tf.Tensor: shape=(), dtype=float32, numpy=0.99287283>

### 2. Nilai Minimum

In [32]:
tf.reduce_min(random_tensor, axis=None)

<tf.Tensor: shape=(), dtype=float32, numpy=0.01690042>

## Penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [36]:
tf.concat([random_tensor, prime_tensor], axis=0)

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[3.8000906e-01, 1.6900420e-02, 4.6101856e-01, 6.3152313e-01,
        9.3237829e-01],
       [5.6035399e-01, 2.3430037e-01, 9.4814479e-01, 4.1055346e-01,
        9.9287283e-01],
       [6.0757577e-01, 8.7704134e-01, 3.6618519e-01, 7.3796856e-01,
        2.4635792e-01],
       [2.1938908e-01, 3.2215166e-01, 6.5801740e-02, 5.9019840e-01,
        5.6537151e-01],
       [9.7212720e-01, 9.1955447e-01, 2.5151372e-02, 2.0070910e-02,
        6.0034311e-01],
       [2.0000000e+00, 3.0000000e+00, 5.0000000e+00, 7.0000000e+00,
        1.1000000e+01],
       [1.3000000e+01, 1.7000000e+01, 1.9000000e+01, 2.3000000e+01,
        2.9000000e+01],
       [3.1000000e+01, 3.7000000e+01, 4.1000000e+01, 4.3000000e+01,
        4.7000000e+01],
       [5.3000000e+01, 5.9000000e+01, 6.1000000e+01, 6.7000000e+01,
        7.1000000e+01],
       [7.3000000e+01, 7.9000000e+01, 8.3000000e+01, 8.9000000e+01,
        9.7000000e+01]], dtype=float32)>

## Sorting dari kedua variable di atas. (descending)

### 1. Sort random_tensor

In [37]:
tf.sort(random_tensor, direction="DESCENDING")

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0.9323783 , 0.63152313, 0.46101856, 0.38000906, 0.01690042],
       [0.99287283, 0.9481448 , 0.560354  , 0.41055346, 0.23430037],
       [0.87704134, 0.73796856, 0.6075758 , 0.3661852 , 0.24635792],
       [0.5901984 , 0.5653715 , 0.32215166, 0.21938908, 0.06580174],
       [0.9721272 , 0.9195545 , 0.6003431 , 0.02515137, 0.02007091]],
      dtype=float32)>

### 2. Sort prime_tensor

In [39]:
tf.sort(prime_tensor, direction="DESCENDING")

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[11.,  7.,  5.,  3.,  2.],
       [29., 23., 19., 17., 13.],
       [47., 43., 41., 37., 31.],
       [71., 67., 61., 59., 53.],
       [97., 89., 83., 79., 73.]], dtype=float32)>